name: Nasa Project CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [mai]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node version 16
        uses: actions/setup@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run build --prefix client
